name: start_chart
version: 0.1.0
description: A chart library for Flutter. Create beautiful charts using a simple and intuitive API.

homepage: https://github.com/bsjung/start_chart

environment:
  sdk: ">=2.0.0-dev.65 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  meta: "^1.1.2"

dev_dependencies:
  flutter_test:
    sdk: flutter
  test: ^1.0.0
